// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADNRrngOAzfp3gvyHVrx-lc62igtXouvM',
    appId: '1:74753917818:web:3da29327b2a72363610cc3',
    messagingSenderId: '74753917818',
    projectId: 'myportfolio-ec367',
    authDomain: 'myportfolio-ec367.firebaseapp.com',
    storageBucket: 'myportfolio-ec367.firebasestorage.app',
    measurementId: 'G-9ZE61G2PEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpWlAa3L5vsr5J_gaYoD1cFJdpH5Pr_Q',
    appId: '1:74753917818:android:2859ce96abb9356b610cc3',
    messagingSenderId: '74753917818',
    projectId: 'myportfolio-ec367',
    storageBucket: 'myportfolio-ec367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxr3BZpyRuqewxuA9XJ5ThK29PX_sfEe4',
    appId: '1:74753917818:ios:ed013a0da36c3120610cc3',
    messagingSenderId: '74753917818',
    projectId: 'myportfolio-ec367',
    storageBucket: 'myportfolio-ec367.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxr3BZpyRuqewxuA9XJ5ThK29PX_sfEe4',
    appId: '1:74753917818:ios:ed013a0da36c3120610cc3',
    messagingSenderId: '74753917818',
    projectId: 'myportfolio-ec367',
    storageBucket: 'myportfolio-ec367.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADNRrngOAzfp3gvyHVrx-lc62igtXouvM',
    appId: '1:74753917818:web:88eef19b9f75213d610cc3',
    messagingSenderId: '74753917818',
    projectId: 'myportfolio-ec367',
    authDomain: 'myportfolio-ec367.firebaseapp.com',
    storageBucket: 'myportfolio-ec367.firebasestorage.app',
    measurementId: 'G-4SC425P7C4',
  );

}